version: '3'
services:
  web:
    build: .
    command: npm run server
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      NODE_NAME: MIKE 
  mongo:
    image: mongo:latest

     